---
title: "BI Card"
output: html_document
params:
  data: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(htmltools)
```

```{css}
.main-container {
max-width:100%;
padding: 0 !important;
}

#header {
display: none;
}

#container {
display: flex;
flex-direction: column;
align-items: center;
}

#desc {
font-size: 20px;
margin: 35px 0 25px 0;
}

a {
font-size: 30px !important;
padding: 10px 30px !important;
}

img {
width: 100%;
}

#linkCall{
line-height:1.1;
}

#linkAlert {
font-size: 0.4em;
}

```


```{r}
tags$link(href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css", rel="stylesheet", integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN", crossorigin="anonymous")

```

```{r}
if (data$LINK == "#") {
  link <- NULL
} else {
  link <- a(
    span(div("Acessar", id = "linkCall"), div("em nova página", id = "linkAlert")),
    href = data$LINK, target = "_blank",
    class = "btn btn-primary", role = "button"
  )
}

div(
  id = "container",
  img(src = data$HEADER),
  div(id = "desc", data$DESC),
  link
)
```
